### ISSUE TITLE
liquibase runner refusing to run on Jenkins Slave

### ISSUE THREAD

**Issue by abc-njspencer** [jenkinsci/liquibase-runner-plugin#10]
Even if we set the Restrict where this project can be run to our slave, it still runs on master.  Which is a problem because firewall rules prevent Jenkins master from accessing Postgres master but not the Jenkins Slave.  Also we don't want that load on the master.  This is the only plugin we have that does this.  I even upgraded to 1.2.1 in hopes that might fix it.  

Is this a bug or by design and can it be fixed?

**Comment by prospero238** [comment]
I can tell you it isn't by explicit design.

I've created a jira issue here:  https://issues.jenkins-ci.org/browse/JENKINS-41002

I'll provide updates on the Jira issue.  

Sorry for your problem, and thank you for giving me the heads up!

**Comment by prospero238** [comment]
After reviewing, this isn't something I can remedy quickly.  You're quite correct in that Jenkins master (as of now) needs to be able to connect to the target database, as liquibase is exercised on the master.

I do, however, have this workaround.  It involves modifying the Jenkins slave connection to setup port forwarding.  I'm assuming that, in your situation, the Jenkins slave and the target postgres server are not one in the same (see below notes otherwise).  I've used this approach elsewhere with success.

* Modify the slave node configuration.  You'll want to change the "Launch method" to be "Launch agent via execution of command on the master".  The launch command should be "ssh [user]@[slave host]  -L5432:[db host]:5432  java -jar [path to slave.jar]".  See Jenkins documentation for info about this configuration.  For us, the important part is the "-L5432:[db host]:5432" which sets up the port forwarding.

* Change your liquibase job configuration so that the JDBC URL is something like "jdbc:postgresql://localhost:5432/sample".  The important part is that the host name is localhost.

Once these steps are done, the Jenkins master's JDBC connection will go over ssh using port forwarding.

Notes:

* I've assumed port 5432 is an available port on Jenkins master.  If it isn't, change the ssh config to be like "-L6666:[db host]:5432" where "6666" is an available port.  Then, in your liquibase configuration, the jdbc url would reflect this port as well, example:  jdbc:postgresql://localhost:6666/sample

* If the Jenkins slave is the same machine as the target database server, you can use "-L5432:localhost:5432" (using "localhost" instead of the database host name).

* Older versions of Jenkins did not have a slave launch option like I've described.  However, you can do the same thing using its "launch via webstart" option.  Ask me for details if you need info.

* There are other potential security restrictions you may run into depending on your server/network setup.  Also, you may want to make your Ops staff aware of what's going on.  There's no shenangians, but I'd keep them in the loop.

**Comment by abc-njspencer** [comment]
Alright.  I appreciate the suggestion on a workaround.  I have passed that to our DevOps team.

**Comment by SnazzyBootMan** [comment]
Appreciate the work around but I am correct in thinking that this will only work on persistent slaves rather than say on on-demand EC2 slaves?

**Comment by robertericreeves** [comment]
We changed the Liquibase Runner Plugin for 1.3.0 significantly. That should resolve this issue.
